// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// roprobit_internal
List roprobit_internal(arma::sp_mat X, arma::sp_mat XXinv, int niterR, int thinR, Rcpp::NumericMatrix initparm, Rcpp::NumericVector ChoiceSetLengthR, Rcpp::NumericVector ROLLengthR, Rcpp::NumericVector GroupIDsR, int nCores, bool demeanY);
RcppExport SEXP _roprobit_roprobit_internal(SEXP XSEXP, SEXP XXinvSEXP, SEXP niterRSEXP, SEXP thinRSEXP, SEXP initparmSEXP, SEXP ChoiceSetLengthRSEXP, SEXP ROLLengthRSEXP, SEXP GroupIDsRSEXP, SEXP nCoresSEXP, SEXP demeanYSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::sp_mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::sp_mat >::type XXinv(XXinvSEXP);
    Rcpp::traits::input_parameter< int >::type niterR(niterRSEXP);
    Rcpp::traits::input_parameter< int >::type thinR(thinRSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type initparm(initparmSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type ChoiceSetLengthR(ChoiceSetLengthRSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type ROLLengthR(ROLLengthRSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type GroupIDsR(GroupIDsRSEXP);
    Rcpp::traits::input_parameter< int >::type nCores(nCoresSEXP);
    Rcpp::traits::input_parameter< bool >::type demeanY(demeanYSEXP);
    rcpp_result_gen = Rcpp::wrap(roprobit_internal(X, XXinv, niterR, thinR, initparm, ChoiceSetLengthR, ROLLengthR, GroupIDsR, nCores, demeanY));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_roprobit_roprobit_internal", (DL_FUNC) &_roprobit_roprobit_internal, 10},
    {NULL, NULL, 0}
};

RcppExport void R_init_roprobit(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
