# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

roprobit_internal <- function(X, XXinv, niterR, thinR, initparm, ChoiceSetLengthR, ROLLengthR, GroupIDsR, nCores, demeanY) {
    .Call(`_roprobit_roprobit_internal`, X, XXinv, niterR, thinR, initparm, ChoiceSetLengthR, ROLLengthR, GroupIDsR, nCores, demeanY)
}

